#!/usr/bin/env bash
# Install nginx on your web-01
# Nginx should be listening on port 80

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx restart
