#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i "28i\add_header X-Served-By '$HOSTNAME';" /etc/nginx/nginx.conf
sudo service nginx restart
